language: ruby
cache:
  bundle: true
  directories:
    - node_modules

notifications:
  email: false

rvm:
  - 2.4.0

env:
  global:
    - RAILS_ENV=test

test:
  adapter: mysql2
  database: picrotium_test
  username: root
  encoding: utf8

services:
  - mysql

install:
  - nvm install
  - npm install -g yarn
  - bundle install --path=vendor/bundle --without development production --retry=3 --jobs=16
  - yarn install

before_script:
  # - bundle exec rails assets:precompile

script:
  # - bundle exec rubocop
  - bundle exec rake db:schema:load
  - bundle exec rspec
